#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cabextract
Version  : 1.10
Release  : 10
URL      : https://www.cabextract.org.uk/cabextract-1.10.tar.gz
Source0  : https://www.cabextract.org.uk/cabextract-1.10.tar.gz
Summary  : A program to extract Microsoft Cabinet files
Group    : Development/Tools
License  : GPL-3.0
Requires: cabextract-bin = %{version}-%{release}
Requires: cabextract-license = %{version}-%{release}
Requires: cabextract-man = %{version}-%{release}
BuildRequires : pkgconfig(libmspack)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Cabinet (.CAB) files are a form of archive, which Microsoft use to
distribute their software, and things like Windows Font Packs. The
cabextract program unpacks these files.

%package bin
Summary: bin components for the cabextract package.
Group: Binaries
Requires: cabextract-license = %{version}-%{release}

%description bin
bin components for the cabextract package.


%package license
Summary: license components for the cabextract package.
Group: Default

%description license
license components for the cabextract package.


%package man
Summary: man components for the cabextract package.
Group: Default

%description man
man components for the cabextract package.


%prep
%setup -q -n cabextract-1.10
cd %{_builddir}/cabextract-1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675712488
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1675712488
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cabextract
cp %{_builddir}/cabextract-%{version}/COPYING %{buildroot}/usr/share/package-licenses/cabextract/31a3d460bb3c7d98845187c716a30db81c44b615 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cabextract

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cabextract/31a3d460bb3c7d98845187c716a30db81c44b615

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cabextract.1
