#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cabextract
Version  : 1.9.1
Release  : 7
URL      : http://www.cabextract.org.uk/cabextract-1.9.1.tar.gz
Source0  : http://www.cabextract.org.uk/cabextract-1.9.1.tar.gz
Summary  : A program to extract Microsoft cabinet (.CAB) files
Group    : Development/Tools
License  : GPL-3.0
Requires: cabextract-bin = %{version}-%{release}
Requires: cabextract-license = %{version}-%{release}
Requires: cabextract-man = %{version}-%{release}
BuildRequires : pkgconfig(libmspack)

%description
Cabinet (.CAB) files are a form of archive, which Microsoft use to
distribute their software, and things like Windows Font Packs. The
cabextract program unpacks these files.

%package bin
Summary: bin components for the cabextract package.
Group: Binaries
Requires: cabextract-license = %{version}-%{release}

%description bin
bin components for the cabextract package.


%package license
Summary: license components for the cabextract package.
Group: Default

%description license
license components for the cabextract package.


%package man
Summary: man components for the cabextract package.
Group: Default

%description man
man components for the cabextract package.


%prep
%setup -q -n cabextract-1.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551719568
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1551719568
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cabextract
cp COPYING %{buildroot}/usr/share/package-licenses/cabextract/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cabextract

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cabextract/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cabextract.1
